### PR TITLE
scenechanger

### PR DESCRIPTION
**Pull request by M-125**
- huge cleanup, fixed offscreen collisions
- Update game.py
- Update README.md
- animation fixes our little girl had animation issues like she walked until the animation was over no matter what and holding two buttons made her do not have animation
- attempt of making a bed
- scenechanger PRESS SPACE TO START GAME sry

### CODE REVIEW

**Review by Razboinicul — APPROVED** [review]
Looks good!

**Comment by M-125** [comment]
Btw how did you review it so fast

**Comment by Razboinicul** [comment]
I read trough the code really fast. It is my job after all

**Comment by M-125** [comment]
Is discord working for you

**Comment by M-125** [comment]
It doesnt work for ne now

**Comment by Razboinicul** [comment]
It is

**Pull request merged**
